name: app-test

on:
  push:
    branches:
      - develop
      - main
      - master
  pull_request:

defaults:
  run:
    working-directory: .

jobs:
  apptests:
    name: Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Clean db before tests
        run: delete_all_nodes
      - name: Sleep for 30 seconds to ensure neo4j is synced
        run: sleep 30s
        shell: bash
      - name: maven clean
        run: mvn verify clean --fail-never
      - name: build work
        run: mvn compile
      - name: Run mvn test
        run: mvn test
      - name: Clean db after tests
        run: delete_all_nodes
